---
micronaut:
  application:
    name: bookshop
---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/bookshop"
    username: "kgalli"
    password: "kgalli"
    driver-class-name: "org.postgresql.Driver"
---
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
