#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

JOOQ_VERSION="3.11.11"
REACTIVE_STREAMS_VERSION="1.0.2"
POSTGRESQL_VERSION="42.2.9"
DOWNLOAD_DIR="$DIR/tmp"

mkdir -p $DOWNLOAD_DIR

curl https://repo1.maven.org/maven2/org/jooq/jooq/$JOOQ_VERSION/jooq-$JOOQ_VERSION.jar \
 --output "$DOWNLOAD_DIR/jooq.jar" --silent
curl https://repo1.maven.org/maven2/org/jooq/jooq-meta/$JOOQ_VERSION/jooq-meta-$JOOQ_VERSION.jar \
 --output "$DOWNLOAD_DIR/jooq-meta.jar" --silent
curl https://repo1.maven.org/maven2/org/jooq/jooq-codegen/$JOOQ_VERSION/jooq-codegen-$JOOQ_VERSION.jar \
 --output "$DOWNLOAD_DIR/jooq-codegen.jar" --silent
curl https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/$REACTIVE_STREAMS_VERSION/reactive-streams-$REACTIVE_STREAMS_VERSION.jar \
 --output "$DOWNLOAD_DIR/reactive-streams.jar" --silent
curl https://repo1.maven.org/maven2/org/postgresql/postgresql/$POSTGRESQL_VERSION/postgresql-$POSTGRESQL_VERSION.jar \
  --output "$DOWNLOAD_DIR/postgresql.jar" --silent

cd $DOWNLOAD_DIR && java -classpath "jooq.jar:jooq-meta.jar:jooq-codegen.jar:reactive-streams.jar:postgresql.jar" \
  org.jooq.codegen.GenerationTool "$DIR/jooq-config.xml"
