/*
 * This file is generated by jOOQ.
 */
package bookshop.jooq;


import bookshop.jooq.tables.Books;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = bookshop.jooq.tables.Books.BOOKS;
}
